apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 1m
  chart:
    spec:
      chart: gatekeeper
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: gatekeeper-system
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
