apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-loki-rancher-desktop
      valuesKey: values.loki.rancher-desktop.yaml
