apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-gatekeeper-rancher-desktop
    files:
      - values.rancher-desktop.yaml
resources:
  - ../base
  - service.yaml
  - serviceMonitor.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: gatekeeper
    path: patch-helm-release.yaml
