apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-gatekeeper-rancher-desktop
      valuesKey: values.rancher-desktop.yaml
