apiVersion: v1
kind: Service
metadata:
  labels:
    app: gatekeeper
    control-plane: controller-manager
    release: gatekeeper
  name: gatekeeper-controller-manager-metrics
spec:
  selector:
    app: gatekeeper
    control-plane: controller-manager
    release: gatekeeper
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gatekeeper
    control-plane: audit-controller
    release: gatekeeper
  name: gatekeeper-audit-controller-metrics
spec:
  selector:
    app: gatekeeper
    control-plane: audit-controller
    release: gatekeeper
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
