apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backstage.yaml
  - cert-manager.yaml
  - cnpg-system.yaml
  - gatekeeper-system.yaml
  - ingress.yaml
  - keycloak.yaml
  - kube-bench.yaml
  - logging.yaml
  - monitoring.yaml
  - tempo.yaml
  - tenant-dank.yaml
