apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: values-kube-state-metrics-rancher-desktop
    files:
      - values.rancher-desktop.yaml
resources:
  - ../base
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta2
      kind: HelmRelease
      name: gatekeeper
    path: patch-helm-release.yaml
