apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  interval: 1m
  chart:
    spec:
      chart: promtail
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
