apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/kube-prometheus-stack/docker-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/loki/docker-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: promtail
  namespace: flux-system
spec:
  dependsOn:
    - name: loki
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/promtail/docker-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/cert-manager/docker-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/cert-manager-issuers/docker-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/ingress-nginx/docker-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/tempo/docker-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/opentelemetry/docker-desktop
  prune: true
  wait: true
  timeout: 10m
