apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 1m
  chart:
    spec:
      chart: tempo
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: tempo
        namespace: tempo
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
