apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-kube-prometheus-stack-rancher-desktop
      valuesKey: values.rancher-desktop.yaml
