prometheus:
  prometheusSpec:
    replicas: 1
    resources:
      requests:
        memory: 520Mi
        cpu: 250m
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    hosts:
      - prometheus.k8s.nephtek.com
    tls:
      - secretName: prometheus-k8s-nephtek-com-cert
        hosts:
          - prometheus.k8s.nephtek.com


grafana:
  additionalDataSources:
    - name: Loki
      url: http://loki-gateway.logging.svc.cluster.local
      type: loki
    - name: Tempo
      url: http://tempo.tempo:3100
      type: tempo
  monitoring:
    rules:
      labels:
        release: kube-prometheus-stack
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    hosts:
      - grafana.k8s.nephtek.com
    tls:
      - secretName: grafana-k8s-nephtek-com-cert
        hosts:
          - grafana.k8s.nephtek.com
