apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-cloudnative-pg-rancher-desktop
      valuesKey: values.rancher-desktop.yaml
