resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
monitoring:
  podMonitorEnabled: true
  grafanaDashboard:
    create: true
cloudnative-pg:
  labels:
    release: kube-prometheus-stack
