apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  valuesFrom:
    - kind: ConfigMap
      name: values-ingress-nginx-rancher-desktop
      valuesKey: values.rancher-desktop.yaml
