apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-tenant-dank
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-tenant-dank
  timeout: 60s
  url: ssh://git@github.com/dan-at-nephtek/flux-tenant-repo
