apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-state-metrics
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
