apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./apps/tempo/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./apps/kube-prometheus-stack/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
