apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/kube-prometheus-stack/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/loki/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: promtail
  namespace: flux-system
spec:
  dependsOn:
    - name: loki
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/promtail/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/gatekeeper/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/cert-manager/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/cert-manager-issuers/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: gatekeeper
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/ingress-nginx/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  dependsOn:
    - name: gatekeeper
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/cloudnative-pg/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/tempo/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: kube-state-metrics
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: kube-prometheus-stack
#      namespace: flux-system
#  interval: 720m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-apps
#  serviceAccountName: kustomize-controller
#  path: ./apps/kube-state-metrics/rancher-desktop
#  prune: true
#  wait: true
#  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-bench
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/kube-bench/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backstage
  namespace: flux-system
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/backstage/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/crds/keycloak
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: keycloak-crds
      namespace: flux-system
    - name: namespaces
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/operators/keycloak/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  dependsOn:
    - name: keycloak-operator
      namespace: flux-system
    - name: cloudnative-pg
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/keycloak/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: capacitor
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: kube-prometheus-stack
#      namespace: flux-system
#  interval: 720m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-apps
#  serviceAccountName: kustomize-controller
#  path: ./apps/capacitor/rancher-desktop
#  prune: true
#  wait: true
#  timeout: 10m
