#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cilium
#  namespace: flux-system
#spec:
#  interval: 720m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./apps/cilium/rancher-desktop
#  prune: true
#  wait: true
#  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  #  dependsOn:
  #    - name: cilium
  #      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/namespaces/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/repositories/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/secrets/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/kube-prometheus-stack/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/loki/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/gatekeeper/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: gatekeeper
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/cert-manager/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: gatekeeper
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/ingress-nginx/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  dependsOn:
    - name: gatekeeper
      namespace: flux-system
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: flux-apps
  serviceAccountName: kustomize-controller
  path: ./apps/cloudnative-pg/rancher-desktop
  prune: true
  wait: true
  timeout: 10m
